//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobileshop.Models2
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobileInfo
    {
        public int mobile_ID { get; set; }
        public int brand_ID { get; set; }
        public string model_Name { get; set; }
        public int mobileTypeId { get; set; }
        public decimal mobile_Price { get; set; }
        public string mobile_Picture { get; set; }
        public Nullable<int> camera { get; set; }
        public Nullable<int> ram { get; set; }
        public Nullable<int> rom { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual mobileType mobileType { get; set; }
    }
}
